name: pullWorkflow

on:
  pull_request:
    branches: [master, dev]
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run lint
        run: npm run lint
      - name: testWithJest
        run: npm run test
